Content has a max-width of 1000px
Sigma-Labs-XYZ/explain-ai pull request #129
Opened 2023-03-14 13:25 UTC by Mariam-mohamed110

Contents have a max-width of 1000px
On screens smaller than 1000px, the app behaves as before
A few minor styling changes for phones for consistency

2023-03-14 13:58 UTC, yuna-iwata requested changes
should the header logo and buttons max width also be set to 1000px?  and also the margins seem to have disappeared between 1000px and phone width
<img width="1175" alt="Screenshot 2023-03-14 at 13 57 54" src="https://user-images.githubusercontent.com/115478706/225024328-60a54324-1c96-48cf-ba52-514b871a179e.png">

2023-03-14 14:03 UTC, s-dilip commented on web/src/Styling/TopicBreadcrumbs/TopicBreadcrumbs.scss
> +    // margin-left: 14.6%;
Can probably get rid of this commented line of code if no longer needed.
```suggestion
 
```

2023-03-14 14:04 UTC, s-dilip commented on web/src/Styling/TopicCard/TopicCard.scss
> +  // margin-top: 20px;
Could remove unneeded code.
```suggestion

```

2023-03-14 14:32 UTC, DomVinyard commented
> should the header logo and buttons max width also be set to 1000px? and also the margins seem to have disappeared between 1000px and phone width
> <img alt="Screenshot 2023-03-14 at 13 57 54" width="1175" src="https://user-images.githubusercontent.com/115478706/225024328-60a54324-1c96-48cf-ba52-514b871a179e.png">

Yes, well spotted - usually we want the same inner element to apply to both the header and the content: 

```
<style>
inner {
    max-width: 1000px;
    margin: 0 auto;
}
</style>

<div className="header-container">
   <div className="inner">
       I am a header
   </div>
<div>
<div className="content-container">
   <div className="inner">
       I am the main container
   </div>
<div>
```

this way we can give the header and the content different background colours that are full width, but the inner element is always consistent

2023-03-14 15:58 UTC, Mariam-mohamed110 commented
> Under `1000px` width, there is no `margin-left` for content (Breadcrumbs, Topic Card, Relation Cards)whatsoever which may not be ideal.
> 
> ![image](https://user-images.githubusercontent.com/93096031/225027833-5e856f21-c4ac-4045-85f0-f2dc4381d2f1.png)

2023-03-14 16:10 UTC, yuna-iwata approved these changes
looks v good 😊

2023-03-15 09:38 UTC, s-dilip approved these changes

2023-03-16 10:29 UTC, Ademsk1 commented on web/src/Global/Header/Header.css
> +  max-width: 1000px;
Very cool !

2023-03-16 10:29 UTC, Ademsk1 approved these changes
Looks good!

2023-03-16 10:31 UTC, merged