Topic page styling
Sigma-Labs-XYZ/explain-ai pull request #97
Opened 2023-03-08 14:27 UTC by Mariam-mohamed110

The topic card and relation card all align, looks visually pleasing

2023-03-08 14:46 UTC, DomVinyard commented
This is a great improvement 👍

2023-03-08 14:46 UTC, DomVinyard approved these changes

2023-03-08 15:23 UTC, bp289 commented on web/src/Styling/TopicCard/TopicCard.css
> +@media screen and (max-width: 1000px) and (min-width: 400px) {
may be a good idea to change this to 600px rather than 400. Ive been investigating some phone sizes and the iphone xr looks a bit squished in: 
<img width="219" alt="image" src="https://user-images.githubusercontent.com/100142251/223754188-2312b9a0-88bc-4c48-9fa5-ff154ab06f3e.png">

2023-03-08 18:28 UTC, Mariam-mohamed110 commented on web/src/Styling/TopicCard/TopicCard.css
> +@media screen and (max-width: 1000px) and (min-width: 400px) {
Ill change the min to 600 like you suggested and see what happens

2023-03-09 14:47 UTC, yuna-iwata commented on web/src/Styling/TopicCard/TopicCard.css
> +@media screen and (max-width: 1000px) and (min-width: 400px) {
the logo and img is still not working in mobile for above 400px to about 530px i think

2023-03-09 14:56 UTC, Ademsk1 commented
I don't think this is ready to be merged yet. Several styling issues are introduced, with respect to topic card.

2023-03-09 14:57 UTC, s-dilip commented on web/src/Styling/TopicCard/TopicCard.css
> +@media screen and (max-width: 1000px) and (min-width: 400px) {
@yuna-iwata yea I tried fixing it but couldn't figure out. Everything else should be fine.

2023-03-09 14:59 UTC, Ademsk1 commented on web/src/Pages/TopicPage/TopicCard/TopicCard.js
> +          <div className="w-56 h-56 -mb-28 mt-5 phone:w-32 phone:h-32 phone:-mb-16 phone: ml-[25%] tablet:w-32 tablet:h-32 tablet:-mb-16">
I think this tailwind is unnecessary, as the sass already handles different phone sizes in media query

2023-03-09 14:59 UTC, yuna-iwata commented on web/src/Styling/TopicCard/TopicCard.css
> +@media screen and (max-width: 1000px) and (min-width: 400px) {
it is working in main so maybe better to revert the css regarding the image back to the original? @s-dilip

2023-03-09 14:59 UTC, Ademsk1 commented on web/src/Pages/TopicPage/TopicCard/TopicCard.js
> +              className="h-full w-full rounded-full"
This line is not needed, the border radius of the div is already at 50%

2023-03-09 15:00 UTC, Ademsk1 commented on web/src/Styling/ErrorMessage/ErrorMessage.css
> -}
This is my pride and joy, and you took it away. You better lawyer up.

2023-03-09 15:01 UTC, Ademsk1 requested changes
Some things are still not working right

2023-03-09 15:08 UTC, Mariam-mohamed110 commented on web/src/Styling/ErrorMessage/ErrorMessage.css
> -}
Adam.... Your pride and joy is still available but just moved elsewhere! How dare me remove it!

2023-03-09 15:08 UTC, s-dilip commented on web/src/Styling/ErrorMessage/ErrorMessage.css
> -}
@Ademsk1 I did not touch it! I have no clue why it got deleted! 😭

2023-03-09 15:13 UTC, s-dilip commented on web/src/Pages/TopicPage/TopicCard/TopicCard.js
> +          <div className="w-56 h-56 -mb-28 mt-5 phone:w-32 phone:h-32 phone:-mb-16 phone: ml-[25%] tablet:w-32 tablet:h-32 tablet:-mb-16">
I tried fixing the css and scss files but it didn't fix anything so I had to use tailwind as a last resort.

2023-03-09 15:21 UTC, s-dilip commented on web/src/Styling/ErrorMessage/ErrorMessage.css
> -}
@Ademsk1 The lines are still there, but the `@-webkit` seems to have been removed. Which is why it appears as though the lines were deleted.

2023-03-09 15:24 UTC, Ademsk1 commented on web/src/Styling/ErrorMessage/ErrorMessage.css
> -}
![standoff](https://user-images.githubusercontent.com/85499621/224071081-8043ae1f-9218-4b04-b168-b36a15364501.gif)

2023-03-09 15:27 UTC, s-dilip commented on web/src/Styling/ErrorMessage/ErrorMessage.css
> -}
@Ademsk1 your animations for the topic card expansion are kinda broken though...

2023-03-09 15:29 UTC, s-dilip commented on web/src/Styling/TopicCard/TopicCard.css
> +@media screen and (max-width: 1000px) and (min-width: 400px) {
@yuna-iwata Main doesn't have the code for div that resizes with the window so it is quite a lot different.

2023-03-09 17:09 UTC, DomVinyard commented on web/src/Styling/ErrorMessage/ErrorMessage.css
> -}
animations are usually not added so early into the dev process as they can often be quite brittle and beak easily, as a general rule it's best to wait to animate until the actual markup structure is settled upon

2023-03-09 17:26 UTC, Ademsk1 approved these changes
This works!

2023-03-09 17:27 UTC, mdapim approved these changes
Went through the code and checked with author, runs on local host no errors, no failures

2023-03-09 18:09 UTC, merged